# Generated by Django 5.0.7 on 2024-07-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_card_taskid"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="taskid",
            field=models.TextField(default="No description provided"),
        ),
    ]
