# Generated by Django 5.0.7 on 2024-07-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_card_taskid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="taskid",
            field=models.CharField(max_length=100),
        ),
    ]
